baseurl = "https://augusteo.com/"
languageCode = "en-us"

title = "Victor Augusteo's Blog"

theme = "ghostwriter"

googleAnalytics = "UA-63044470-1"
disqusShortname = "augusteo"

[Author]
  name = "Victor Augusteo"
  profile = "/page/about/"

[Taxonomies]
  tag = "tags"

[Params]
  intro = true
  headline = "Victor Augusteo"
  description = "Tech. Games. Learning."
  name = "Victor Augusteo"
  aboutAuthor = "Mostly making iOS app with Swift. Enjoys tinkering with Linux, Ruby, JavaScript and other shiny stuff."

[Permalinks]
  post = "/:filename/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/page/about/"
  weight = 2
